extends:
  - recommended

rules:
  rule/path-required-must-exist:
    where:
      - subject:
          type: Parameter
          property: in
        assertions:
          const: path
    subject:
      type: Parameter
      property: required
    assertions:
      defined: true
    message: Required must exist in path parameters.
    severity: error
  rule/path-parameter-must-required:
    where:
      - subject:
          type: Parameter
          property: in
        assertions:
          const: path
    subject:
      type: Parameter
      property: required
    assertions:
      const: true
    message: Path parameter must be required true.
    suggest:
      - "true"
    severity: error

apis:
  main@1:
    root: ./openapi/openapi.yaml
    rules:
      no-unused-components: warn

features.openapi:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
