openapi: 3.1.0
info:
  version: 0.0.14
  title: OCPI

  contact:
    email: dev@plugo.co.jp
    url: https://plugo.co.jp/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://redocly.github.io/openapi-template/logo.png
  description: OCPI 2.2.1 specification

servers:
  - url: https://www.example.com
    description: Development server
tags:
  - name: Sessions
    description: |
      Module Identifier: sessions

      Data owner: CPO

      Type: Functional Module

      The Session object describes one charging session. The Session object is owned by the CPO back-end system, and can be GET from the CPO system, or pushed by the CPO to another system.
  - name: Commands
    description: |
      Module Identifier: commands

      Type: Functional Module

      The Commands module enables remote commands to be sent to a Location/EVSE. The following commands are supported:
      - CANCEL_RESERVATION • RESERVE_NOW
      - START_SESSION
      - STOP_SESSION
      - UNLOCK_CONNECTOR

      See CommandType for a description of the different commands. Use the UNLOCK_CONNECTOR command with care, please read
      the note at CommandType.

      Module dependency: Locations module, Sessions module

paths:
  /sessions:
    $ref: paths/sessions.yaml
  /sessions/{session_id}/charging_preferences:
    $ref: paths/sessions_{session_id}_charging_preferences.yaml
  /sessions/{country_code}/{party_id}/{session_id}:
    $ref: paths/sessions_{country_code}_{party_id}_{session_id}.yaml
  /commands/START_SESSION:
    $ref: paths/commands_start_session.yaml
  /commands/STOP_SESSION:
    $ref: paths/commands_stop_session.yaml
  /commands/{command}/{uid}:
    $ref: paths/commands_{command}_{uid}.yaml
  /tokens/{country_code}/{party_id}/{token_uid}:
    $ref: paths/tokens_{country_code}_{party_id}_{token_uid}.yaml
  /versions:
    $ref: paths/versions.yaml
  /{version}:
    $ref: paths/{version}.yaml
  /credentials:
    $ref: paths/credentials.yaml
  /locations:
    $ref: paths/locations.yaml
  /locations/{location_id}:
    $ref: paths/locations_{location_id}.yaml
  /locations/{location_id}/{evse_uid}:
    $ref: paths/locations_{location_id}_{evse_uid}.yaml
  /locations/{location_id}/{evse_uid}/{connector_id}:
    $ref: paths/locations_{location_id}_{evse_uid}_{connector_id}.yaml
  /tariffs:
    $ref: paths/tariffs.yaml
  /cdrs:
    $ref: paths/cdrs.yaml
  /cdrs/{cdr_id}:
    $ref: paths/cdrs_{cdr_id}.yaml
  /chargingprofiles/{session_id}:
    $ref: paths/chargingprofiles_{session_id}.yaml

components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
