name: Publish d.ts package to npmjs
on:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #     - feature/ci # for debug

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: echo 'Install yq...'
      - run: curl -LJO https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
      - run: sudo mv yq_linux_amd64 /usr/local/bin/yq
      - run: sudo chmod a+x /usr/local/bin/yq
      - run: echo 'NPM install & build...'
      - run: npm ci
      - run: npm run build
      - run: export __OAS_VERSION=`/usr/bin/yq e '.info.version' openapi/openapi.yaml`
      - run: cd dist/dts && npm init -y --scope=@plugoinc --name=ocpi-openapi-dts --version=$__OAS_VERSION --main=dist/dts/schema.d.ts && cat package.json

      # - run: echo 'Publish to npmjs...'
      # - run: npm publish -access publich
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
